// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ledger.proto

package ledger

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionParams) Reset()         { *m = TransactionParams{} }
func (m *TransactionParams) String() string { return proto.CompactTextString(m) }
func (*TransactionParams) ProtoMessage()    {}
func (*TransactionParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_63585974d4c6a2c4, []int{0}
}

func (m *TransactionParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionParams.Unmarshal(m, b)
}
func (m *TransactionParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionParams.Marshal(b, m, deterministic)
}
func (m *TransactionParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionParams.Merge(m, src)
}
func (m *TransactionParams) XXX_Size() int {
	return xxx_messageInfo_TransactionParams.Size(m)
}
func (m *TransactionParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionParams.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionParams proto.InternalMessageInfo

type Transaction struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            string   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Amount               float64  `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_63585974d4c6a2c4, []int{1}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Transaction) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*TransactionParams)(nil), "ledger.TransactionParams")
	proto.RegisterType((*Transaction)(nil), "ledger.Transaction")
}

func init() { proto.RegisterFile("ledger.proto", fileDescriptor_63585974d4c6a2c4) }

var fileDescriptor_63585974d4c6a2c4 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x49, 0x4d, 0x49,
	0x4f, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x84, 0xb9, 0x04,
	0x43, 0x8a, 0x12, 0xf3, 0x8a, 0x13, 0x93, 0x4b, 0x32, 0xf3, 0xf3, 0x02, 0x12, 0x8b, 0x12, 0x73,
	0x8b, 0x95, 0x82, 0xb9, 0xb8, 0x91, 0x04, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0x98, 0x32, 0x53, 0x84, 0x64, 0xb8, 0x38, 0x4b, 0x32, 0x73, 0x53, 0x8b,
	0x4b, 0x12, 0x73, 0x0b, 0x24, 0x98, 0xc0, 0xc2, 0x08, 0x01, 0x21, 0x31, 0x2e, 0xb6, 0xc4, 0xdc,
	0xfc, 0xd2, 0xbc, 0x12, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xc6, 0x20, 0x28, 0xcf, 0xc8, 0x9f, 0x8b,
	0xcd, 0x07, 0x6c, 0xa7, 0x90, 0x2b, 0x17, 0xbf, 0x7b, 0x6a, 0x09, 0x92, 0x0d, 0xc5, 0x42, 0x92,
	0x7a, 0x50, 0xd7, 0x61, 0x38, 0x46, 0x4a, 0x18, 0x8b, 0x94, 0x12, 0x83, 0x01, 0x63, 0x12, 0x1b,
	0xd8, 0x27, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0x79, 0x3e, 0x00, 0xd9, 0x00, 0x00,
	0x00,
}
